#!/usr/bin/env bash
# Builds @heroui/react and @heroui/styles and publishes them to the
# `release` orphan branch as a minimal two-package pnpm workspace, so
# consumers can install straight from git:
#
#   "@heroui/react": "git+ssh://git@github.com/<org>/base-ui.git#release"
#   "@heroui/styles": "git+ssh://git@github.com/<org>/base-ui.git#release"
#
# Why a two-package workspace and not npm-style standalone packages:
# @heroui/react depends on @heroui/styles via "workspace:*", which only
# resolves inside a real pnpm workspace. Rewriting it to a pinned semver
# range would let each package install in isolation, but then a react
# release and its matching styles release could drift out of sync
# silently. Shipping both together, always in lockstep, is the safer
# default for an internal design system with one integrator.
#
# Safety: the orphan branch is assembled in a separate `git worktree`
# (its own directory, same repo) — never on the checkout that invoked
# this script. A failure here leaves your working tree untouched.
#
# Run from the repo root: ./scripts/release.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ -n "$(git status --porcelain)" ]; then
  echo "Erro: working tree sujo. Commit ou stash antes de rodar o release." >&2
  exit 1
fi

CURRENT_COMMIT="$(git rev-parse --short HEAD)"
CURRENT_BRANCH="$(git branch --show-current)"

echo "==> Building @heroui/styles and @heroui/react (from $CURRENT_BRANCH @ $CURRENT_COMMIT)"
pnpm --filter @heroui/styles build
pnpm --filter @heroui/react build --tsc

STAGE_DIR="$(mktemp -d)"
WORKTREE_DIR="$(mktemp -d -t base-ui-release)"
rmdir "$WORKTREE_DIR" # git worktree add requires the target not to exist yet

cleanup() {
  git worktree remove --force "$WORKTREE_DIR" > /dev/null 2>&1 || true
  rm -rf "$STAGE_DIR"
}
trap cleanup EXIT

echo "==> Staging package.json (publish-time exports) via clean-package"
for pkg in react styles; do
  mkdir -p "$STAGE_DIR/packages/$pkg"
  (
    cd "packages/$pkg"
    npx clean-package > /dev/null
    if [ "$pkg" = "react" ]; then
      node scripts/update-exports.mjs
    fi
    cp package.json "$STAGE_DIR/packages/$pkg/package.json"
    npx clean-package restore > /dev/null
  )
  cp -R "packages/$pkg/dist" "$STAGE_DIR/packages/$pkg/dist"
done

cat > "$STAGE_DIR/pnpm-workspace.yaml" <<'EOF'
packages:
  - "packages/*"
EOF

cat > "$STAGE_DIR/package.json" <<'EOF'
{
  "name": "base-ui-release",
  "private": true,
  "description": "Built artifacts only — generated by scripts/release.sh. Do not edit by hand."
}
EOF

echo "==> Assembling orphan 'release' branch in a separate worktree"
if git show-ref --verify --quiet refs/heads/release; then
  git worktree add -q "$WORKTREE_DIR" release
else
  git worktree add -q --orphan -b release "$WORKTREE_DIR"
fi

(
  cd "$WORKTREE_DIR"
  find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
  cp -R "$STAGE_DIR"/. .
  git add -A
  if git diff --cached --quiet; then
    echo "Nada mudou desde o último release — pulando commit."
  else
    git commit -q -m "release: $CURRENT_COMMIT" \
      -m "Built from $CURRENT_BRANCH @ $CURRENT_COMMIT. Generated by scripts/release.sh — do not edit by hand."
  fi
)

echo ""
echo "✓ Branch 'release' updated locally (based on $CURRENT_COMMIT). Push with:"
echo "    git push origin release --force"
echo ""
echo "Consumers install with:"
echo '    "@heroui/react": "git+ssh://git@github.com/<org>/base-ui.git#release"'
echo '    "@heroui/styles": "git+ssh://git@github.com/<org>/base-ui.git#release"'
